[package]
name = "bbk_sorgu"
version = "1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tempfile = "3.2"
webbrowser = "0.5"