name: Test Scripts on Arch Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install necessary packages for Arch Linux compatibility
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Run Cachy script
        run: |
          ./cachy.sh
          exit_code=$?
          echo "Exit code for Cachy script: $exit_code"
          exit $exit_code

      - name: Run Chaotic script
        run: |
          ./chaotic.sh
          exit_code=$?
          echo "Exit code for Chaotic script: $exit_code"
          exit $exit_code

      - name: Run SDDM script
        run: |
          ./sddm.sh
          exit_code=$?
          echo "Exit code for SDDM script: $exit_code"
          exit $exit_code